export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';

export const REFRESH_ACCESS_TOKEN_REQUEST = 'REFRESH_ACCESS_TOKEN_REQUEST';
export const REFRESH_ACCESS_TOKEN_SUCCESS = 'REFRESH_ACCESS_TOKEN_SUCCESS';
export const REFRESH_ACCESS_TOKEN_FAILURE = 'REFRESH_ACCESS_TOKEN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_AND_REDIRECT = 'LOGOUT_AND_REDIRECT';

export const FETCH_ARTICLE_LIST_REQUEST = 'FETCH_ARTICLE_LIST_REQUEST';
export const FETCH_ARTICLE_LIST_SUCCESS = 'FETCH_ARTICLE_LIST_SUCCESS';
export const FETCH_ARTICLE_LIST_FAILURE = 'FETCH_ARTICLE_LIST_FAILURE';

export const FETCH_COMMENT_LIST_REQUEST = 'FETCH_COMMENT_LIST_REQUEST';
export const FETCH_COMMENT_LIST_SUCCESS = 'FETCH_COMMENT_LIST_SUCCESS';
export const FETCH_COMMENT_LIST_FAILURE = 'FETCH_COMMENT_LIST_FAILURE';

export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE';

export const FETCH_REPLY_LIST_REQUEST = 'FETCH_REPLY_LIST_REQUEST';
export const FETCH_REPLY_LIST_SUCCESS = 'FETCH_REPLY_LIST_SUCCESS';
export const FETCH_REPLY_LIST_FAILURE = 'FETCH_REPLY_LIST_FAILURE';

export const POST_REPLY_REQUEST = 'POST_REPLY_REQUEST';
export const POST_REPLY_SUCCESS = 'POST_REPLY_SUCCESS';
export const POST_REPLY_FAILURE = 'POST_REPLY_FAILURE';

export const FETCH_TAG_LIST_REQUEST = 'FETCH_TAG_LIST_REQUEST';
export const FETCH_TAG_LIST_SUCCESS = 'FETCH_TAG_LIST_SUCCESS';
export const FETCH_TAG_LIST_FAILURE = 'FETCH_TAG_LIST_FAILURE';